### ISSUE TITLE
Consider use `arr-filter`?

### ISSUE THREAD

**Issue by tunnckoCore** [twada/universal-deep-strict-equal#8]
Hi, that package is great, thanks!
I just want to suggest you use https://github.com/jonschlinkert/arr-filter, it's pretty faster - even than native array filter. It may be big and deep dependency, because it use `make-iterator` - I can understand.

**Comment by twada** [comment]
@tunnckoCore Thank you for your suggestion. `arr-filter` looks nice, however, as you know, I do not want to add extra deep dependencies that are not necessary for most of environments.

**Comment by tunnckoCore** [comment]
Yea, it's understandable. Same here, I also using it in a few places, but I'm considering to remove it exactly because that deep dep. tree.

But yea, it may worth or not. It can add some perf improvement, but it gets that improvement in installing time in node or respectively downloading more bytes in browser. So yea. Okey :)
